ERROR - 2023-03-04 20:17:25 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'acuaticostoscanini' in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'acuaticostoscan...', 3306, '', 0)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\Database.php(67): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#4 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(97): CodeIgniter\Database\Config::forge(NULL)
#5 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(69): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#6 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#7 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#8 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'acuaticostoscanini' in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\Database.php(67): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(97): CodeIgniter\Database\Config::forge(NULL)
#4 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(69): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
#5 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#6 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#7 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#8 {main}
CRITICAL - 2023-03-04 20:17:25 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'acuaticostoscanini'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\Database.php(67): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\Config.php(109): CodeIgniter\Database\Database->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))
 3 SYSTEMPATH\Database\Seeder.php(97): CodeIgniter\Database\Config::forge(null)
 4 SYSTEMPATH\Commands\Database\Seed.php(69): CodeIgniter\Database\Seeder->__construct(Object(Config\Database))
 5 SYSTEMPATH\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run([...])
 6 SYSTEMPATH\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', [...])
 7 ROOTPATH\spark(97): CodeIgniter\CLI\Console->run()
ERROR - 2023-03-04 20:17:58 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `ca...', 0)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ca...')
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ca...')
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(1801): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ca...', NULL, false)
#4 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(2192): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\acuaticostoscanini\app\Database\Seeds\CategoriaSeeder.php(24): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(146): App\Database\Seeds\CategoriaSeeder->run()
#7 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-03-04 20:31:05 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`acuaticos`.`cliente`, CONSTRAINT `fk_cliente_tipo_cliente1` FOREIGN KEY (`tipo_cliente`) REFERENCES `tipo_cliente` (`codigo`) ON DELETE NO ACTION ON UPDATE NO ACTION) in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `cl...', 0)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `cl...')
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `cl...')
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(1801): CodeIgniter\Database\BaseConnection->query('INSERT INTO `cl...', NULL, false)
#4 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(2192): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\acuaticostoscanini\app\Database\Seeds\ClienteSeeder.php(29): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(146): App\Database\Seeds\ClienteSeeder->run()
#7 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-03-04 21:12:04 --> mysqli_sql_exception: Table 'acuaticos.usuarios' doesn't exist in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(1801): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(2192): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\acuaticostoscanini\app\Database\Seeds\UsuarioSeeder.php(38): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(146): App\Database\Seeds\UsuarioSeeder->run()
#7 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-03-04 21:12:39 --> mysqli_sql_exception: Unknown column 'direccion' in 'field list' in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(1801): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', NULL, false)
#4 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(2192): CodeIgniter\Database\BaseBuilder->batchExecute('_insertBatch', 100)
#5 C:\xampp\htdocs\acuaticostoscanini\app\Database\Seeds\UsuarioSeeder.php(38): CodeIgniter\Database\BaseBuilder->insertBatch(Array)
#6 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(146): App\Database\Seeds\UsuarioSeeder->run()
#7 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#8 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#9 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#10 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#11 {main}
ERROR - 2023-03-04 21:22:17 --> mysqli_sql_exception: Table 'acuaticos.usuarios' doesn't exist in C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\acuaticostoscanini\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\acuaticostoscanini\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\acuaticostoscanini\app\Database\Seeds\FacturaSeeder.php(15): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\acuaticostoscanini\system\Database\Seeder.php(146): App\Database\Seeds\FacturaSeeder->run()
#6 C:\xampp\htdocs\acuaticostoscanini\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\xampp\htdocs\acuaticostoscanini\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\xampp\htdocs\acuaticostoscanini\spark(97): CodeIgniter\CLI\Console->run()
#10 {main}
